baseurl = "https://mshibanami.github.io/randomtube"
title = "RandomTube"

ignoreFiles = ["\\.(sass|scss|less|ts|coffee)$"]


[params]
  Author = "mshibanami"

  iOSAppID = "id923695245"
  SupportTwitterID = "random_tube"

  DefaultLanguage = "en"

  # サポートする言語
  [params.Languages]
    en = "English"
    ja = "日本語"

  # 言語に対応する国コード (Open Graph 等用)
  [params.Countries]
    en = "US"
    ja = "JP"
